export const initialQuestions = [

  // ── MATEMATIKA ──────────────────────────────────────────
  { id: "m001", subject: "Matematika", question: "Koliko je 347 + 256?", options: ["593", "603", "613", "583"], answer: 1 },
  { id: "m002", subject: "Matematika", question: "Koliko je 800 - 364?", options: ["436", "446", "426", "436"], answer: 0 },
  { id: "m003", subject: "Matematika", question: "Koliko je 24 × 3?", options: ["62", "72", "68", "76"], answer: 1 },
  { id: "m004", subject: "Matematika", question: "Koliko je 96 ÷ 4?", options: ["22", "26", "24", "28"], answer: 2 },
  { id: "m005", subject: "Matematika", question: "Koji broj je najbliži broju 500: 489, 513, 501 ili 498?", options: ["489", "513", "501", "498"], answer: 2 },
  { id: "m006", subject: "Matematika", question: "Koliko je 1000 - 1?", options: ["998", "999", "1001", "990"], answer: 1 },
  { id: "m007", subject: "Matematika", question: "Koliko ima cifara u broju 4728?", options: ["3", "5", "4", "6"], answer: 2 },
  { id: "m008", subject: "Matematika", question: "Koji je najmanji četvorocifreni broj?", options: ["1111", "1000", "9999", "0001"], answer: 1 },
  { id: "m009", subject: "Matematika", question: "Koliko je 5 × 8?", options: ["35", "45", "40", "48"], answer: 2 },
  { id: "m010", subject: "Matematika", question: "Ako u korpi ima 36 jabuka i podelimo ih na 4 dece jednako, koliko dobija svako dete?", options: ["8", "10", "9", "7"], answer: 2 },
  { id: "m011", subject: "Matematika", question: "Koliko je 7 × 7?", options: ["42", "49", "56", "48"], answer: 1 },
  { id: "m012", subject: "Matematika", question: "Polovina od 120 je?", options: ["50", "70", "60", "55"], answer: 2 },
  { id: "m013", subject: "Matematika", question: "Trećina od 90 je?", options: ["20", "30", "45", "25"], answer: 1 },
  { id: "m014", subject: "Matematika", question: "Koliko je 456 + 544?", options: ["990", "1000", "1010", "900"], answer: 1 },
  { id: "m015", subject: "Matematika", question: "Koliko stepeni ima pravi ugao?", options: ["45°", "180°", "90°", "360°"], answer: 2 },
  { id: "m016", subject: "Matematika", question: "Figura sa 4 jednake stranice i 4 prava ugla zove se?", options: ["Pravougaonik", "Romb", "Kvadrat", "Trapez"], answer: 2 },
  { id: "m017", subject: "Matematika", question: "Obim kvadrata čija je stranica 6 cm je?", options: ["12 cm", "36 cm", "24 cm", "18 cm"], answer: 2 },
  { id: "m018", subject: "Matematika", question: "Površina pravougaonika 5 cm × 4 cm je?", options: ["18 cm²", "20 cm²", "9 cm²", "22 cm²"], answer: 1 },
  { id: "m019", subject: "Matematika", question: "Koliko je 9 × 6?", options: ["54", "63", "48", "56"], answer: 0 },
  { id: "m020", subject: "Matematika", question: "Broj 2748 zaokružen na stotice je?", options: ["2700", "2750", "2800", "3000"], answer: 2 },
  { id: "m021", subject: "Matematika", question: "Koliko je 63 ÷ 7?", options: ["8", "9", "7", "6"], answer: 1 },
  { id: "m022", subject: "Matematika", question: "Koji broj nedostaje: 3, 6, 9, __, 15?", options: ["11", "13", "12", "10"], answer: 2 },
  { id: "m023", subject: "Matematika", question: "Koliko minuta ima 2 sata?", options: ["100", "120", "90", "60"], answer: 1 },
  { id: "m024", subject: "Matematika", question: "Koliko je 1 km u metrima?", options: ["100 m", "10 m", "1000 m", "500 m"], answer: 2 },
  { id: "m025", subject: "Matematika", question: "Ana ima 3 paketa sa po 12 olovaka. Koliko olovaka ima ukupno?", options: ["15", "36", "30", "48"], answer: 1 },
  { id: "m026", subject: "Matematika", question: "Koliko je 4000 + 300 + 20 + 7?", options: ["4237", "4327", "4372", "4732"], answer: 1 },
  { id: "m027", subject: "Matematika", question: "Koji broj je paran: 13, 27, 34, 51?", options: ["13", "27", "34", "51"], answer: 2 },
  { id: "m028", subject: "Matematika", question: "Koliko je 100 × 8?", options: ["80", "180", "800", "8000"], answer: 2 },
  { id: "m029", subject: "Matematika", question: "Zbir uglova trougla iznosi?", options: ["90°", "270°", "180°", "360°"], answer: 2 },
  { id: "m030", subject: "Matematika", question: "Koliko je 48 ÷ 6?", options: ["6", "9", "8", "7"], answer: 2 },

  // ── SRPSKI JEZIK ────────────────────────────────────────
  { id: "s001", subject: "Srpski jezik", question: "Koja je reč imenica: trčati, brzo, selo, veseo?", options: ["trčati", "brzo", "selo", "veseo"], answer: 2 },
  { id: "s002", subject: "Srpski jezik", question: "Koja je reč glagol: kuća, pevati, mali, tamo?", options: ["kuća", "pevati", "mali", "tamo"], answer: 1 },
  { id: "s003", subject: "Srpski jezik", question: "Koja je reč pridev: dečak, skakati, visok, gore?", options: ["dečak", "skakati", "visok", "gore"], answer: 2 },
  { id: "s004", subject: "Srpski jezik", question: "Koliko slova ima srpska azbuka?", options: ["26", "30", "32", "28"], answer: 2 },
  { id: "s005", subject: "Srpski jezik", question: "Koje slovo dolazi posle slova Д u azbuci?", options: ["Ђ", "Е", "З", "Г"], answer: 0 },
  { id: "s006", subject: "Srpski jezik", question: "Reč 'mama' ima koliko slogova?", options: ["1", "3", "2", "4"], answer: 2 },
  { id: "s007", subject: "Srpski jezik", question: "Kako se zove tačka na kraju rečenice?", options: ["Zarez", "Uzvik", "Tačka", "Upitnik"], answer: 2 },
  { id: "s008", subject: "Srpski jezik", question: "Na kraju upitne rečenice stoji?", options: ["Tačka", "Upitnik", "Uzvičnik", "Zarez"], answer: 1 },
  { id: "s009", subject: "Srpski jezik", question: "Koja od ovih reči je u množini: mačka, deca, pas, kuća?", options: ["mačka", "deca", "pas", "kuća"], answer: 1 },
  { id: "s010", subject: "Srpski jezik", question: "'Knjiga' je reč koja označava?", options: ["Radnju", "Osobinu", "Biće", "Predmet"], answer: 3 },
  { id: "s011", subject: "Srpski jezik", question: "Koji rod je imenica 'sunce'?", options: ["Muški", "Ženski", "Srednji", "Nema rod"], answer: 2 },
  { id: "s012", subject: "Srpski jezik", question: "Suprotno od reči 'velik' je?", options: ["Visok", "Mali", "Debeo", "Brz"], answer: 1 },
  { id: "s013", subject: "Srpski jezik", question: "Reč koja ima isto značenje kao 'hrabar' je?", options: ["Kukavičan", "Spor", "Smeo", "Tih"], answer: 2 },
  { id: "s014", subject: "Srpski jezik", question: "Koja rečenica je ispravno napisana?", options: ["ide marko u školu.", "Ide Marko u školu.", "ide Marko u školu.", "Ide marko u školu."], answer: 1 },
  { id: "s015", subject: "Srpski jezik", question: "Koliko samoglasnika ima srpska azbuka?", options: ["4", "6", "5", "7"], answer: 2 },
  { id: "s016", subject: "Srpski jezik", question: "Koji je samoglasnik u reči 'mrak'?", options: ["M", "R", "A", "K"], answer: 2 },
  { id: "s017", subject: "Srpski jezik", question: "Kako se zove autor bajke 'Pepeljuga'?", options: ["Andersen", "Grofa Tolstoja", "Braća Grim", "Vuk Stefanović Karadžić"], answer: 2 },
  { id: "s018", subject: "Srpski jezik", question: "Množina reči 'dete' je?", options: ["Detes", "Deca", "Detovi", "Deteta"], answer: 1 },
  { id: "s019", subject: "Srpski jezik", question: "Koja reč je napisana pravilno?", options: ["džep", "džep", "Džep", "dZep"], answer: 0 },
  { id: "s020", subject: "Srpski jezik", question: "Kako se zove pesma koja se peva deci za uspavljivanje?", options: ["Basna", "Uspavanка", "Bajka", "Priča"], answer: 1 },
  { id: "s021", subject: "Srpski jezik", question: "Reči 'tata' i 'otac' su?", options: ["Antonimi", "Sinonimi", "Homonimi", "Različite reči"], answer: 1 },
  { id: "s022", subject: "Srpski jezik", question: "Koja interpunkcija se stavlja pri nabrajanju?", options: ["Tačka", "Upitnik", "Zarez", "Crtica"], answer: 2 },
  { id: "s023", subject: "Srpski jezik", question: "Glagol 'pisati' u sadašnjem vremenu za 'ja' je?", options: ["pisao", "pisaću", "pišem", "pisah"], answer: 2 },
  { id: "s024", subject: "Srpski jezik", question: "Suprotno od 'dan' je?", options: ["Jutro", "Noć", "Veče", "Podne"], answer: 1 },
  { id: "s025", subject: "Srpski jezik", question: "Reč 'škola' ima koliko slova?", options: ["4", "6", "5", "7"], answer: 2 },
  { id: "s026", subject: "Srpski jezik", question: "Koje slovo je na početku azbuke?", options: ["Б", "В", "А", "Г"], answer: 2 },
  { id: "s027", subject: "Srpski jezik", question: "Kako se zove književna vrsta u kojoj životinje govore i imaju osobine ljudi?", options: ["Bajka", "Basna", "Roman", "Pesma"], answer: 1 },
  { id: "s028", subject: "Srpski jezik", question: "Pridev 'lep' u ženskom rodu je?", options: ["lepa", "lepа", "lepo", "lepi"], answer: 0 },
  { id: "s029", subject: "Srpski jezik", question: "Koliko reči ima rečenica 'Mačka spava na krevetu.'?", options: ["3", "5", "4", "6"], answer: 2 },
  { id: "s030", subject: "Srpski jezik", question: "Koja reč je glagol: 'trčanje', 'trčati', 'trkač', 'brz'?", options: ["trčanje", "trčati", "trkač", "brz"], answer: 1 },

  // ── PRIRODA I DRUŠTVO ───────────────────────────────────
  { id: "p001", subject: "Priroda i društvo", question: "Koliko kontinenata ima na Zemlji?", options: ["5", "6", "7", "8"], answer: 2 },
  { id: "p002", subject: "Priroda i društvo", question: "Koji je glavni grad Srbije?", options: ["Novi Sad", "Niš", "Beograd", "Kragujevac"], answer: 2 },
  { id: "p003", subject: "Priroda i društvo", question: "Reka koja protiče kroz Beograd je?", options: ["Morava", "Drina", "Dunav", "Nišava"], answer: 2 },
  { id: "p004", subject: "Priroda i društvo", question: "Koliko meseci ima godina?", options: ["10", "11", "12", "13"], answer: 2 },
  { id: "p005", subject: "Priroda i društvo", question: "Koji mesec ima 28 ili 29 dana?", options: ["Januar", "Februar", "Mart", "April"], answer: 1 },
  { id: "p006", subject: "Priroda i društvo", question: "Kojoj grupi živih bića pripada ptica?", options: ["Sisari", "Gmizavci", "Ptice", "Ribe"], answer: 2 },
  { id: "p007", subject: "Priroda i društvo", question: "Šta biljkama treba za fotosintezu?", options: ["Meso i voda", "Sunčeva svetlost, voda i CO₂", "Kiseonik i šećer", "Zemlja i vetar"], answer: 1 },
  { id: "p008", subject: "Priroda i društvo", question: "Koja planeta je najbliža Suncu?", options: ["Venera", "Zemlja", "Merkur", "Mars"], answer: 2 },
  { id: "p009", subject: "Priroda i društvo", question: "Koliko dana ima jedna sedmica?", options: ["5", "6", "7", "8"], answer: 2 },
  { id: "p010", subject: "Priroda i društvo", question: "Koji organ pumpa krv kroz telo?", options: ["Pluća", "Jetra", "Srce", "Bubreg"], answer: 2 },
  { id: "p011", subject: "Priroda i društvo", question: "Čime dišu ribe?", options: ["Plućima", "Škrgama", "Kožom", "Nosom"], answer: 1 },
  { id: "p012", subject: "Priroda i društvo", question: "Koja je najveća životinja na kopnu?", options: ["Žirafa", "Nilski konj", "Slon", "Nosorog"], answer: 2 },
  { id: "p013", subject: "Priroda i društvo", question: "Koje godišnje doba dolazi posle zime?", options: ["Jesen", "Leto", "Proleće", "Nema promene"], answer: 2 },
  { id: "p014", subject: "Priroda i društvo", question: "Od čega se pravi hleb?", options: ["Kukuruza", "Pirinča", "Pšeničnog brašna", "Ječma"], answer: 2 },
  { id: "p015", subject: "Priroda i društvo", question: "Koji gas udišemo a bez kojeg ne možemo živeti?", options: ["Ugljovodonik", "Azot", "Kiseonik", "Ugljen dioksid"], answer: 2 },
  { id: "p016", subject: "Priroda i društvo", question: "Najduža reka u Srbiji je?", options: ["Sava", "Drina", "Velika Morava", "Dunav u Srbiji"], answer: 2 },
  { id: "p017", subject: "Priroda i društvo", question: "Koji organ koristimo za varenje hrane?", options: ["Srce", "Stomak", "Pluća", "Mozak"], answer: 1 },
  { id: "p018", subject: "Priroda i društvo", question: "Šta je fotosinteza?", options: ["Disanje biljaka", "Stvaranje hrane uz pomoć svetlosti", "Rast biljaka", "Razmnožavanje biljaka"], answer: 1 },
  { id: "p019", subject: "Priroda i društvo", question: "Koliko kostiju ima odrasli čovek (približno)?", options: ["106", "206", "306", "406"], answer: 1 },
  { id: "p020", subject: "Priroda i društvo", question: "Koja životinja je poznata kao 'kralj životinja'?", options: ["Tigar", "Medved", "Lav", "Gepard"], answer: 2 },
  { id: "p021", subject: "Priroda i društvo", question: "Šta se slavilo 15. februara u Srbiji?", options: ["Dan škole", "Dan državnosti Srbije", "Dan majki", "Nova godina"], answer: 1 },
  { id: "p022", subject: "Priroda i društvo", question: "Koja strana sveta je suprotna od severa?", options: ["Istok", "Zapad", "Jug", "Severoistok"], answer: 2 },
  { id: "p023", subject: "Priroda i društvo", question: "Kompas pokazuje prema kojoj strani sveta?", options: ["Jugu", "Istoku", "Severu", "Zapadu"], answer: 2 },
  { id: "p024", subject: "Priroda i društvo", question: "Koja je najduža reka na svetu?", options: ["Amazon", "Nil", "Jangce", "Misisipi"], answer: 1 },
  { id: "p025", subject: "Priroda i društvo", question: "Koliko planeta ima u Sunčevom sistemu?", options: ["7", "8", "9", "10"], answer: 1 },
  { id: "p026", subject: "Priroda i društvo", question: "Šta su listopadna stabla?", options: ["Stabla koja rastu brzo", "Stabla koja gube lišće zimi", "Stabla sa četinama", "Stabla koja nikad ne rastu"], answer: 1 },
  { id: "p027", subject: "Priroda i društvo", question: "Ko donosi zakone u Srbiji?", options: ["Predsednik", "Vlada", "Skupština", "Sudovi"], answer: 2 },
  { id: "p028", subject: "Priroda i društvo", question: "Kako se zove naša planeta?", options: ["Mars", "Venera", "Zemlja", "Saturn"], answer: 2 },
  { id: "p029", subject: "Priroda i društvo", question: "Koja životinja ne spava tokom zimskog sna: medved, jež, zec ili puh?", options: ["Medved", "Jež", "Zec", "Puh"], answer: 2 },
  { id: "p030", subject: "Priroda i društvo", question: "Gde žive pingvini?", options: ["Na Arktiku", "U Africi", "Na Antarktiku", "U Aziji"], answer: 2 },

  // ── NEMAČKI JEZIK ────────────────────────────────────────
  { id: "n001", subject: "Nemački jezik", question: "Kako se kaže 'dobar dan' na nemačkom?", options: ["Guten Abend", "Guten Morgen", "Guten Tag", "Auf Wiedersehen"], answer: 2 },
  { id: "n002", subject: "Nemački jezik", question: "Kako se kaže 'hvala' na nemačkom?", options: ["Bitte", "Danke", "Entschuldigung", "Hallo"], answer: 1 },
  { id: "n003", subject: "Nemački jezik", question: "Kako se kaže 'jedan' na nemačkom?", options: ["Zwei", "Drei", "Eins", "Vier"], answer: 2 },
  { id: "n004", subject: "Nemački jezik", question: "Kako se kaže 'škola' na nemačkom?", options: ["Haus", "Schule", "Buch", "Tisch"], answer: 1 },
  { id: "n005", subject: "Nemački jezik", question: "Kako se kaže 'pas' na nemačkom?", options: ["Katze", "Maus", "Hund", "Vogel"], answer: 2 },
  { id: "n006", subject: "Nemački jezik", question: "Kako se kaže 'mačka' na nemačkom?", options: ["Hund", "Katze", "Fisch", "Pferd"], answer: 1 },
  { id: "n007", subject: "Nemački jezik", question: "Kako se kaže 'jabuka' na nemačkom?", options: ["Birne", "Banane", "Apfel", "Orange"], answer: 2 },
  { id: "n008", subject: "Nemački jezik", question: "Kako se kaže 'majka' na nemačkom?", options: ["Vater", "Bruder", "Mutter", "Schwester"], answer: 2 },
  { id: "n009", subject: "Nemački jezik", question: "Kako se kaže 'otac' na nemačkom?", options: ["Mutter", "Vater", "Sohn", "Onkel"], answer: 1 },
  { id: "n010", subject: "Nemački jezik", question: "Kako se kaže 'dobro jutro' na nemačkom?", options: ["Guten Tag", "Gute Nacht", "Guten Morgen", "Hallo"], answer: 2 },
  { id: "n011", subject: "Nemački jezik", question: "Kako se kaže 'laku noć' na nemačkom?", options: ["Guten Morgen", "Gute Nacht", "Guten Abend", "Tschüss"], answer: 1 },
  { id: "n012", subject: "Nemački jezik", question: "Kako se kaže 'knjiga' na nemačkom?", options: ["Heft", "Stift", "Buch", "Tafel"], answer: 2 },
  { id: "n013", subject: "Nemački jezik", question: "Kako se kaže 'dva' na nemačkom?", options: ["Eins", "Drei", "Zwei", "Vier"], answer: 2 },
  { id: "n014", subject: "Nemački jezik", question: "Kako se kaže 'deset' na nemačkom?", options: ["Acht", "Neun", "Zehn", "Sieben"], answer: 2 },
  { id: "n015", subject: "Nemački jezik", question: "Kako se kaže 'crvena' na nemačkom?", options: ["Blau", "Grün", "Rot", "Gelb"], answer: 2 },
  { id: "n016", subject: "Nemački jezik", question: "Kako se kaže 'plava' na nemačkom?", options: ["Rot", "Blau", "Grün", "Weiß"], answer: 1 },
  { id: "n017", subject: "Nemački jezik", question: "Kako se kaže 'kuća' na nemačkom?", options: ["Auto", "Haus", "Baum", "Blume"], answer: 1 },
  { id: "n018", subject: "Nemački jezik", question: "Kako se kaže 'drvo' na nemačkom?", options: ["Blume", "Gras", "Baum", "Stein"], answer: 2 },
  { id: "n019", subject: "Nemački jezik", question: "Kako se kaže 'prijatelj' na nemačkom?", options: ["Feind", "Freund", "Lehrer", "Schüler"], answer: 1 },
  { id: "n020", subject: "Nemački jezik", question: "Kako se kaže 'učiteljica' na nemačkom?", options: ["Schülerin", "Mutter", "Lehrerin", "Freundin"], answer: 2 },
  { id: "n021", subject: "Nemački jezik", question: "Kako se kaže 'zelena' na nemačkom?", options: ["Rot", "Blau", "Grün", "Schwarz"], answer: 2 },
  { id: "n022", subject: "Nemački jezik", question: "Šta znači reč 'Wasser'?", options: ["Vatра", "Vazduh", "Voda", "Zemlja"], answer: 2 },
  { id: "n023", subject: "Nemački jezik", question: "Šta znači reč 'Brot'?", options: ["Mleko", "Hleb", "Sir", "Meso"], answer: 1 },
  { id: "n024", subject: "Nemački jezik", question: "Kako se kaže 'doviđenja' na nemačkom?", options: ["Hallo", "Danke", "Auf Wiedersehen", "Bitte"], answer: 2 },
  { id: "n025", subject: "Nemački jezik", question: "Šta znači reč 'Schule'?", options: ["Igra", "Škola", "Kuća", "Knjiga"], answer: 1 },
  { id: "n026", subject: "Nemački jezik", question: "Kako se kaže 'pet' na nemačkom?", options: ["Vier", "Sechs", "Fünf", "Drei"], answer: 2 },
  { id: "n027", subject: "Nemački jezik", question: "Šta znači 'Ich heiße...'?", options: ["Imam ... godina", "Ja se zovem...", "Ja sam iz...", "Ja volim..."], answer: 1 },
  { id: "n028", subject: "Nemački jezik", question: "Šta znači 'Wie alt bist du?'?", options: ["Kako se zoveš?", "Odakle si?", "Koliko imaš godina?", "Gde živiš?"], answer: 2 },
  { id: "n029", subject: "Nemački jezik", question: "Kako se kaže 'sveska' na nemačkom?", options: ["Buch", "Heft", "Stift", "Lineal"], answer: 1 },
  { id: "n030", subject: "Nemački jezik", question: "Šta znači 'Ich verstehe nicht'?", options: ["Razumem", "Ne čujem", "Ne razumem", "Ne znam"], answer: 2 },
];
