export const initialQuestions = [

  // ── MATEMATIKA ──────────────────────────────────────────
  { id: "m001", subject: "Matematika", question: "Koliko je 347 + 256?", options: ["593", "603", "613", "583"], answer: 1 },
  { id: "m002", subject: "Matematika", question: "Koliko je 800 - 364?", options: ["436", "446", "426", "436"], answer: 0 },
  { id: "m003", subject: "Matematika", question: "Koliko je 24 × 3?", options: ["62", "72", "68", "76"], answer: 1 },
  { id: "m004", subject: "Matematika", question: "Koliko je 96 ÷ 4?", options: ["22", "26", "24", "28"], answer: 2 },
  { id: "m005", subject: "Matematika", question: "Koji broj je najbliži broju 500: 489, 513, 501 ili 498?", options: ["489", "513", "501", "498"], answer: 2 },
  { id: "m006", subject: "Matematika", question: "Koliko je 1000 - 1?", options: ["998", "999", "1001", "990"], answer: 1 },
  { id: "m007", subject: "Matematika", question: "Koliko ima cifara u broju 4728?", options: ["3", "5", "4", "6"], answer: 2 },
  { id: "m008", subject: "Matematika", question: "Koji je najmanji četvorocifreni broj?", options: ["1111", "1000", "9999", "0001"], answer: 1 },
  { id: "m009", subject: "Matematika", question: "Koliko je 5 × 8?", options: ["35", "45", "40", "48"], answer: 2 },
  { id: "m010", subject: "Matematika", question: "Ako u korpi ima 36 jabuka i podelimo ih na 4 dece jednako, koliko dobija svako dete?", options: ["8", "10", "9", "7"], answer: 2 },
  { id: "m011", subject: "Matematika", question: "Koliko je 7 × 7?", options: ["42", "49", "56", "48"], answer: 1 },
  { id: "m012", subject: "Matematika", question: "Polovina od 120 je?", options: ["50", "70", "60", "55"], answer: 2 },
  { id: "m013", subject: "Matematika", question: "Trećina od 90 je?", options: ["20", "30", "45", "25"], answer: 1 },
  { id: "m014", subject: "Matematika", question: "Koliko je 456 + 544?", options: ["990", "1000", "1010", "900"], answer: 1 },
  { id: "m015", subject: "Matematika", question: "Koliko stepeni ima pravi ugao?", options: ["45°", "180°", "90°", "360°"], answer: 2 },
  { id: "m016", subject: "Matematika", question: "Figura sa 4 jednake stranice i 4 prava ugla zove se?", options: ["Pravougaonik", "Romb", "Kvadrat", "Trapez"], answer: 2 },
  { id: "m017", subject: "Matematika", question: "Obim kvadrata čija je stranica 6 cm je?", options: ["12 cm", "36 cm", "24 cm", "18 cm"], answer: 1 },
  { id: "m018", subject: "Matematika", question: "Površina pravougaonika 5 cm × 4 cm je?", options: ["18 cm²", "20 cm²", "9 cm²", "22 cm²"], answer: 1 },
  { id: "m019", subject: "Matematika", question: "Koliko je 9 × 6?", options: ["54", "63", "48", "56"], answer: 0 },
  { id: "m020", subject: "Matematika", question: "Broj 2748 zaokružen na stotice je?", options: ["2700", "2750", "2800", "3000"], answer: 0 },
  { id: "m021", subject: "Matematika", question: "Koliko je 63 ÷ 7?", options: ["8", "9", "7", "6"], answer: 1 },
  { id: "m022", subject: "Matematika", question: "Koji broj nedostaje: 3, 6, 9, __, 15?", options: ["11", "13", "12", "10"], answer: 2 },
  { id: "m023", subject: "Matematika", question: "Koliko minuta ima 2 sata?", options: ["100", "120", "90", "60"], answer: 1 },
  { id: "m024", subject: "Matematika", question: "Koliko je 1 km u metrima?", options: ["100 m", "10 m", "1000 m", "500 m"], answer: 2 },
  { id: "m025", subject: "Matematika", question: "Ana ima 3 paketa sa po 12 olovaka. Koliko olovaka ima ukupno?", options: ["15", "36", "30", "48"], answer: 1 },
  { id: "m026", subject: "Matematika", question: "Koliko je 4000 + 300 + 20 + 7?", options: ["4237", "4327", "4372", "4732"], answer: 1 },
  { id: "m027", subject: "Matematika", question: "Koji broj je paran: 13, 27, 34, 51?", options: ["13", "27", "34", "51"], answer: 2 },
  { id: "m028", subject: "Matematika", question: "Koliko je 100 × 8?", options: ["80", "180", "800", "8000"], answer: 2 },
  { id: "m029", subject: "Matematika", question: "Zbir uglova trougla iznosi?", options: ["90°", "270°", "180°", "360°"], answer: 2 },
  { id: "m030", subject: "Matematika", question: "Koliko je 48 ÷ 6?", options: ["6", "9", "8", "7"], answer: 2 },
  { id: "m031", subject: "Matematika", question: "Koliko je 25 × 4?", options: ["90", "100", "110", "80"], answer: 1 },
  { id: "m032", subject: "Matematika", question: "Koliko je 144 ÷ 12?", options: ["10", "14", "12", "11"], answer: 2 },
  { id: "m033", subject: "Matematika", question: "Koliko je 999 + 1?", options: ["1000", "1001", "998", "1100"], answer: 0 },
  { id: "m034", subject: "Matematika", question: "Četvrtina od 80 je?", options: ["20", "40", "10", "25"], answer: 0 },
  { id: "m035", subject: "Matematika", question: "Koliko je 6 × 9?", options: ["54", "63", "56", "48"], answer: 0 },
  { id: "m036", subject: "Matematika", question: "Koji broj je neparan: 14, 22, 37, 50?", options: ["14", "22", "37", "50"], answer: 2 },
  { id: "m037", subject: "Matematika", question: "Koliko sekundi ima jedan minut?", options: ["100", "30", "60", "120"], answer: 2 },
  { id: "m038", subject: "Matematika", question: "Koliko sati ima jedan dan?", options: ["12", "24", "48", "36"], answer: 1 },
  { id: "m039", subject: "Matematika", question: "Broj 3562 zaokružen na hiljade je?", options: ["3000", "4000", "3500", "3600"], answer: 0 },
  { id: "m040", subject: "Matematika", question: "Koliko je 7 × 8?", options: ["54", "63", "56", "49"], answer: 2 },
  { id: "m041", subject: "Matematika", question: "Koliko je 500 - 275?", options: ["235", "225", "215", "245"], answer: 1 },
  { id: "m042", subject: "Matematika", question: "Obim pravougaonika 6 cm × 3 cm je?", options: ["9 cm", "18 cm", "36 cm", "12 cm"], answer: 1 },
  { id: "m043", subject: "Matematika", question: "Površina kvadrata čija je stranica 5 cm je?", options: ["20 cm²", "10 cm²", "25 cm²", "15 cm²"], answer: 2 },
  { id: "m044", subject: "Matematika", question: "Koliko je 1 kg u gramima?", options: ["100 g", "500 g", "1000 g", "250 g"], answer: 2 },
  { id: "m045", subject: "Matematika", question: "Koji broj nedostaje: 2, 4, 8, __, 32?", options: ["12", "16", "14", "18"], answer: 1 },
  { id: "m046", subject: "Matematika", question: "Koliko je 300 × 3?", options: ["900", "90", "9000", "600"], answer: 0 },
  { id: "m047", subject: "Matematika", question: "Marko ima 5 redova sa po 8 karata. Koliko karata ima ukupno?", options: ["13", "35", "40", "45"], answer: 2 },
  { id: "m048", subject: "Matematika", question: "Koliko je 72 ÷ 8?", options: ["8", "7", "9", "6"], answer: 2 },
  { id: "m049", subject: "Matematika", question: "Koji je najveći četvorocifreni broj?", options: ["9000", "9990", "9999", "1000"], answer: 2 },
  { id: "m050", subject: "Matematika", question: "Koliko je 456 - 123?", options: ["323", "343", "333", "313"], answer: 2 },
  { id: "m051", subject: "Matematika", question: "Koliko je 11 × 11?", options: ["111", "121", "131", "112"], answer: 1 },
  { id: "m052", subject: "Matematika", question: "Koliko dana ima prosta godina?", options: ["355", "360", "365", "366"], answer: 2 },
  { id: "m053", subject: "Matematika", question: "Koliko dana ima prestupna godina?", options: ["355", "360", "365", "366"], answer: 3 },
  { id: "m054", subject: "Matematika", question: "Koji broj nedostaje: 100, 90, 80, __, 60?", options: ["65", "75", "70", "85"], answer: 2 },
  { id: "m055", subject: "Matematika", question: "Koliko je 1 L  u mililitrima?", options: ["100 ml", "500 ml", "1000 ml", "250 ml"], answer: 2 },
  { id: "m056", subject: "Matematika", question: "Trougao ima koliko stranica?", options: ["2", "4", "3", "5"], answer: 2 },
  { id: "m057", subject: "Matematika", question: "Koliko je 8 × 8?", options: ["56", "72", "64", "48"], answer: 2 },
  { id: "m058", subject: "Matematika", question: "Koliko je 1000 + 2000?", options: ["2000", "3000", "4000", "1200"], answer: 1 },
  { id: "m059", subject: "Matematika", question: "U jednom paketu ima 6 jaja. Koliko jaja ima u 7 paketa?", options: ["13", "36", "42", "48"], answer: 2 },
  { id: "m060", subject: "Matematika", question: "Koliko je 540 ÷ 6?", options: ["80", "100", "90", "60"], answer: 2 },
  { id: "m061", subject: "Matematika", question: "Koliko je 4 × 25?", options: ["75", "100", "80", "125"], answer: 1 },
  { id: "m062", subject: "Matematika", question: "Koja cifra označava hiljade u broju 7483?", options: ["4", "8", "7", "3"], answer: 2 },
  { id: "m063", subject: "Matematika", question: "Koliko je 250 + 750?", options: ["900", "1100", "1000", "800"], answer: 2 },
  { id: "m064", subject: "Matematika", question: "Ako je kvadrat stranice 4 cm, koliki je njegov obim?", options: ["8 cm", "12 cm", "16 cm", "20 cm"], answer: 2 },
  { id: "m065", subject: "Matematika", question: "Koliko je 9 × 9?", options: ["72", "81", "90", "63"], answer: 1 },
  { id: "m066", subject: "Matematika", question: "Koji broj nedostaje: 5, 10, 15, 20, __?", options: ["22", "30", "25", "28"], answer: 2 },
  { id: "m067", subject: "Matematika", question: "Koliko je 600 ÷ 3?", options: ["100", "300", "200", "150"], answer: 2 },
  { id: "m068", subject: "Matematika", question: "Šta je polovina od 300?", options: ["100", "200", "150", "50"], answer: 2 },
  { id: "m069", subject: "Matematika", question: "Koliko je 13 × 3?", options: ["36", "42", "39", "33"], answer: 2 },
  { id: "m070", subject: "Matematika", question: "Pravougaonik ima koliko stranica?", options: ["3", "5", "4", "6"], answer: 2 },
  { id: "m071", subject: "Matematika", question: "Koliko je 7000 - 1000?", options: ["5000", "7000", "6000", "8000"], answer: 2 },
  { id: "m072", subject: "Matematika", question: "Koliko je 15 × 2?", options: ["25", "35", "30", "20"], answer: 2 },
  { id: "m073", subject: "Matematika", question: "Ako voz kreće u 8:00 i putuje 3 sata, kada stiže?", options: ["10:00", "12:00", "11:00", "9:00"], answer: 2 },
  { id: "m074", subject: "Matematika", question: "Koliko je 56 ÷ 7?", options: ["6", "9", "8", "7"], answer: 2 },
  { id: "m075", subject: "Matematika", question: "Broj 5000 + 400 + 60 + 3 je?", options: ["5643", "5436", "5463", "5346"], answer: 2 },
  { id: "m076", subject: "Matematika", question: "Koliko je 3 × 3 × 3?", options: ["9", "18", "27", "12"], answer: 2 },
  { id: "m077", subject: "Matematika", question: "Koji broj je deljiv sa 5: 13, 21, 35, 44?", options: ["13", "21", "35", "44"], answer: 2 },
  { id: "m078", subject: "Matematika", question: "Koliko je 2000 - 500?", options: ["1000", "1700", "1500", "1200"], answer: 2 },
  { id: "m079", subject: "Matematika", question: "Šta je trećina od 60?", options: ["15", "25", "20", "30"], answer: 2 },
  { id: "m080", subject: "Matematika", question: "Koliko je 99 + 99?", options: ["189", "199", "198", "188"], answer: 2 },
  { id: "m081", subject: "Matematika", question: "Koliko je 1 dm u centimetrima?", options: ["100 cm", "1 cm", "10 cm", "1000 cm"], answer: 2 },
  { id: "m082", subject: "Matematika", question: "Koji broj nedostaje: 1, 3, 5, 7, __?", options: ["8", "10", "9", "11"], answer: 2 },
  { id: "m083", subject: "Matematika", question: "Koliko je 400 + 60 + 5?", options: ["4065", "465", "456", "645"], answer: 1 },
  { id: "m084", subject: "Matematika", question: "Ako ima 48 učenika u 4 odeljenja, koliko ih je u svakom?", options: ["10", "14", "12", "16"], answer: 2 },
  { id: "m085", subject: "Matematika", question: "Koliko je 10 × 10?", options: ["20", "1000", "100", "110"], answer: 2 },
  { id: "m086", subject: "Matematika", question: "Ugao manji od 90° je?", options: ["Tupi ugao", "Pravi ugao", "Šiljasti ugao", "Ravni ugao"], answer: 2 },
  { id: "m087", subject: "Matematika", question: "Koliko je 5000 + 5000?", options: ["5000", "15000", "10000", "50000"], answer: 2 },
  { id: "m088", subject: "Matematika", question: "Koliko je 81 ÷ 9?", options: ["7", "8", "9", "10"], answer: 2 },
  { id: "m089", subject: "Matematika", question: "Koliko je 6 × 6?", options: ["30", "42", "36", "32"], answer: 2 },
  { id: "m090", subject: "Matematika", question: "Koja cifra označava desetice u broju 6789?", options: ["6", "7", "9", "8"], answer: 3 },
  { id: "m091", subject: "Matematika", question: "Koliko je 14 × 5?", options: ["65", "60", "70", "75"], answer: 2 },
  { id: "m092", subject: "Matematika", question: "Koji broj je između 499 i 501?", options: ["498", "502", "500", "499"], answer: 2 },
  { id: "m093", subject: "Matematika", question: "Koliko je 1200 ÷ 4?", options: ["200", "400", "300", "350"], answer: 2 },
  { id: "m094", subject: "Matematika", question: "Koliko je 3 × 12?", options: ["30", "42", "36", "33"], answer: 2 },
  { id: "m095", subject: "Matematika", question: "Površina pravougaonika 8 cm × 3 cm je?", options: ["11 cm²", "22 cm²", "24 cm²", "16 cm²"], answer: 2 },
  { id: "m096", subject: "Matematika", question: "Koliko je 4500 - 500?", options: ["3500", "5000", "4000", "4500"], answer: 2 },
  { id: "m097", subject: "Matematika", question: "Koliko je 7 × 4?", options: ["24", "21", "28", "32"], answer: 2 },
  { id: "m098", subject: "Matematika", question: "Broj deljiv i sa 2 i sa 5 je?", options: ["12", "25", "30", "14"], answer: 2 },
  { id: "m099", subject: "Matematika", question: "Koliko je 5 + 5 + 5 + 5 + 5?", options: ["20", "30", "25", "15"], answer: 2 },
  { id: "m100", subject: "Matematika", question: "Ugao veći od 90° a manji od 180° je?", options: ["Šiljasti", "Pravi", "Tupi", "Ravni"], answer: 2 },

  // ── SRPSKI JEZIK ────────────────────────────────────────
  { id: "s001", subject: "Srpski jezik", question: "Koja je reč imenica: trčati, brzo, selo, veseo?", options: ["trčati", "brzo", "selo", "veseo"], answer: 2 },
  { id: "s002", subject: "Srpski jezik", question: "Koja je reč glagol: kuća, pevati, mali, tamo?", options: ["kuća", "pevati", "mali", "tamo"], answer: 1 },
  { id: "s003", subject: "Srpski jezik", question: "Koja je reč pridev: dečak, skakati, visok, gore?", options: ["dečak", "skakati", "visok", "gore"], answer: 2 },
  { id: "s004", subject: "Srpski jezik", question: "Koliko slova ima srpska azbuka?", options: ["26", "30", "32", "28"], answer: 1 },
  { id: "s005", subject: "Srpski jezik", question: "Koje slovo dolazi posle slova Д u azbuci?", options: ["Ђ", "Е", "З", "Г"], answer: 0 },
  { id: "s006", subject: "Srpski jezik", question: "Reč 'mama' ima koliko slogova?", options: ["1", "3", "2", "4"], answer: 2 },
  { id: "s007", subject: "Srpski jezik", question: "Kako se zove tačka na kraju rečenice?", options: ["Zarez", "Uzvik", "Tačka", "Upitnik"], answer: 2 },
  { id: "s008", subject: "Srpski jezik", question: "Na kraju upitne rečenice stoji?", options: ["Tačka", "Upitnik", "Uzvičnik", "Zarez"], answer: 1 },
  { id: "s009", subject: "Srpski jezik", question: "Koja od ovih reči je u množini: mačka, deca, pas, kuća?", options: ["mačka", "deca", "pas", "kuća"], answer: 1 },
  { id: "s010", subject: "Srpski jezik", question: "'Knjiga' je reč koja označava?", options: ["Radnju", "Osobinu", "Biće", "Predmet"], answer: 3 },
  { id: "s011", subject: "Srpski jezik", question: "Koji rod je imenica 'sunce'?", options: ["Muški", "Ženski", "Srednji", "Nema rod"], answer: 2 },
  { id: "s012", subject: "Srpski jezik", question: "Suprotno od reči 'veliki' je?", options: ["Visok", "Mali", "Debeo", "Brz"], answer: 1 },
  { id: "s013", subject: "Srpski jezik", question: "Reč koja ima isto značenje kao 'hrabar' je?", options: ["Kukavičan", "Spor", "Smeo", "Tih"], answer: 2 },
  { id: "s014", subject: "Srpski jezik", question: "Koja rečenica je ispravno napisana?", options: ["ide marko u školu.", "Ide Marko u školu.", "ide Marko u školu.", "Ide marko u školu."], answer: 1 },
  { id: "s015", subject: "Srpski jezik", question: "Koliko samoglasnika ima srpska azbuka?", options: ["4", "6", "5", "7"], answer: 2 },
  { id: "s016", subject: "Srpski jezik", question: "Koji je samoglasnik u reči 'mrak'?", options: ["M", "R", "A", "K"], answer: 2 },
  { id: "s017", subject: "Srpski jezik", question: "Kako se zove autor bajke 'Pepeljuga'?", options: ["Andersen", "Grofa Tolstoja", "Braća Grim", "Vuk Stefanović Karadžić"], answer: 2 },
  { id: "s018", subject: "Srpski jezik", question: "Množina reči 'dete' je?", options: ["Detes", "Deca", "Detovi", "Deteta"], answer: 1 },
  { id: "s019", subject: "Srpski jezik", question: "Koja reč je napisana pravilno?", options: ["džep", "džeps", "Džep", "dZep"], answer: 0 },
  { id: "s020", subject: "Srpski jezik", question: "Kako se zove pesma koja se peva deci za uspavljivanje?", options: ["Basna", "Uspavanка", "Bajka", "Priča"], answer: 1 },
  { id: "s021", subject: "Srpski jezik", question: "Reči 'tata' i 'otac' su?", options: ["Antonimi", "Sinonimi", "Homonimi", "Različite reči"], answer: 1 },
  { id: "s022", subject: "Srpski jezik", question: "Koja interpunkcija se stavlja pri nabrajanju?", options: ["Tačka", "Upitnik", "Zarez", "Crtica"], answer: 2 },
  { id: "s023", subject: "Srpski jezik", question: "Glagol 'pisati' u sadašnjem vremenu za 'ja' je?", options: ["pisao", "pisaću", "pišem", "pisah"], answer: 2 },
  { id: "s024", subject: "Srpski jezik", question: "Suprotno od 'dan' je?", options: ["Jutro", "Noć", "Veče", "Podne"], answer: 1 },
  { id: "s025", subject: "Srpski jezik", question: "Reč 'škola' ima koliko slova?", options: ["4", "6", "5", "7"], answer: 2 },
  { id: "s026", subject: "Srpski jezik", question: "Koje slovo je na početku azbuke?", options: ["Б", "В", "А", "Г"], answer: 2 },
  { id: "s027", subject: "Srpski jezik", question: "Kako se zove književna vrsta u kojoj životinje govore i imaju osobine ljudi?", options: ["Bajka", "Basna", "Roman", "Pesma"], answer: 1 },
  { id: "s028", subject: "Srpski jezik", question: "Pridev 'lep' u ženskom rodu je?", options: ["lepa", "lepotа", "lepo", "lepi"], answer: 0 },
  { id: "s029", subject: "Srpski jezik", question: "Koliko reči ima rečenica 'Mačka spava na krevetu.'?", options: ["3", "5", "4", "6"], answer: 2 },
  { id: "s030", subject: "Srpski jezik", question: "Koja reč je glagol: 'trčanje', 'trčati', 'trkač', 'brz'?", options: ["trčanje", "trčati", "trkač", "brz"], answer: 1 },
  { id: "s031", subject: "Srpski jezik", question: "Koji rod je imenica 'tata'?", options: ["Ženski", "Srednji", "Muški", "Nema rod"], answer: 2 },
  { id: "s032", subject: "Srpski jezik", question: "Suprotno od reči 'visok' je?", options: ["Debeo", "Mršav", "Nizak", "Spor"], answer: 2 },
  { id: "s033", subject: "Srpski jezik", question: "Koja je reč prilog: lepo, lepota, lep, lepiti?", options: ["lepota", "lep", "lepo", "lepiti"], answer: 2 },
  { id: "s034", subject: "Srpski jezik", question: "Rečenica koja nešto pita naziva se?", options: ["Izjavna", "Uzvična", "Upitna", "Zapovedna"], answer: 2 },
  { id: "s035", subject: "Srpski jezik", question: "Kako se piše ime na početku rečenice?", options: ["Malim slovom", "Pisanim slovom", "Velikim slovom", "Svejedno"], answer: 2 },
  { id: "s036", subject: "Srpski jezik", question: "Koji je antonim reči 'brz'?", options: ["Hitar", "Lagan", "Spor", "Tih"], answer: 2 },
  { id: "s037", subject: "Srpski jezik", question: "Reč 'dečak' je kojeg roda?", options: ["Ženskog", "Srednjeg", "Muškog", "Nema rod"], answer: 2 },
  { id: "s038", subject: "Srpski jezik", question: "Koliko slogova ima reč 'automobil'?", options: ["3", "5", "4", "6"], answer: 2 },
  { id: "s039", subject: "Srpski jezik", question: "Glagol 'trčati' opisuje?", options: ["Osobinu", "Predmet", "Radnju", "Biće"], answer: 2 },
  { id: "s040", subject: "Srpski jezik", question: "Koja reč je imenica: plava, nebo, leteti, brzo?", options: ["plava", "nebo", "leteti", "brzo"], answer: 1 },
  { id: "s041", subject: "Srpski jezik", question: "Šta označava uzvičnik?", options: ["Pitanje", "Pauzu", "Uzvik ili naređenje", "Kraj teksta"], answer: 2 },
  { id: "s042", subject: "Srpski jezik", question: "Reč 'brat' u množini je?", options: ["bratovi", "brati", "braća", "bratevi"], answer: 2 },
  { id: "s043", subject: "Srpski jezik", question: "Koja vrsta reči opisuje imenicu?", options: ["Glagol", "Prilog", "Pridev", "Veznik"], answer: 2 },
  { id: "s044", subject: "Srpski jezik", question: "Koja reč ima suprotno značenje od 'toplо'?", options: ["Vruće", "Hladno", "Sveže", "Mokro"], answer: 1 },
  { id: "s045", subject: "Srpski jezik", question: "Kako se naziva prva reč u rečenici?", options: ["Predikat", "Subjekat", "Objekat", "Priloška odredba"], answer: 1 },
  { id: "s046", subject: "Srpski jezik", question: "Koliko slova ima reč 'prijatelj'?", options: ["7", "9", "8", "10"], answer: 2 },
  { id: "s047", subject: "Srpski jezik", question: "Reč 'leteti' je?", options: ["Imenica", "Pridev", "Glagol", "Prilog"], answer: 2 },
  { id: "s048", subject: "Srpski jezik", question: "Suprotno od 'tužan' je?", options: ["Spor", "Srećan", "Miran", "Tih"], answer: 1 },
  { id: "s049", subject: "Srpski jezik", question: "Bajku 'Ružno pače' napisao je?", options: ["Braća Grim", "Vuk Karadžić", "Hans Kristijan Andersen", "Laza Lazarević"], answer: 2 },
  { id: "s050", subject: "Srpski jezik", question: "Imenica 'mačka' je kojeg roda?", options: ["Muškog", "Ženskog", "Srednjeg", "Nema rod"], answer: 1 },
  { id: "s051", subject: "Srpski jezik", question: "Reč 'zeleno' je?", options: ["Imenica", "Glagol", "Pridev u sr. rodu", "Prilog"], answer: 2 },
  { id: "s052", subject: "Srpski jezik", question: "Koji znak stoji na kraju uzvične rečenice?", options: ["Tačka", "Upitnik", "Zarez", "Uzvičnik"], answer: 3 },
  { id: "s053", subject: "Srpski jezik", question: "Glagol 'pišem' je u kom vremenu?", options: ["Prošlom", "Budućem", "Sadašnjem", "Davno prošlom"], answer: 2 },
  { id: "s054", subject: "Srpski jezik", question: "Imenica 'nebo' je kojeg roda?", options: ["Muškog", "Ženskog", "Srednjeg", "Nema rod"], answer: 2 },
  { id: "s055", subject: "Srpski jezik", question: "Koje slovo je poslednje u srpskoj azbuci?", options: ["Ш", "Ж", "Џ", "Ч"], answer: 0 },
  { id: "s056", subject: "Srpski jezik", question: "Pridev 'lep' u muškom rodu množine je?", options: ["lepa", "lepo", "lepi", "lepih"], answer: 2 },
  { id: "s057", subject: "Srpski jezik", question: "Koja reč je sinonim za 'vetar'?", options: ["Kiša", "Sneg", "Vetrić", "Bura"], answer: 3 },
  { id: "s058", subject: "Srpski jezik", question: "Reč 'pisati' u budućem vremenu za 'ja' je?", options: ["pisao sam", "pišem", "pisaću", "pisah"], answer: 2 },
  { id: "s059", subject: "Srpski jezik", question: "Koja reč je u jednini: deca, oči, stolovi, knjiga?", options: ["deca", "oči", "stolovi", "knjiga"], answer: 3 },
  { id: "s060", subject: "Srpski jezik", question: "Reč 'majka' i reč 'mama' su?", options: ["Antonimi", "Sinonimi", "Homonimi", "Različite vrste reči"], answer: 1 },
  { id: "s061", subject: "Srpski jezik", question: "Koliko slogova ima reč 'škola'?", options: ["1", "3", "2", "4"], answer: 2 },
  { id: "s062", subject: "Srpski jezik", question: "Koja je reč ispravno napisana?", options: ["Srbija", "srbija", "SRBIJA", "sRBIJA"], answer: 0 },
  { id: "s063", subject: "Srpski jezik", question: "Rečenica 'Idi u sobu!' je?", options: ["Izjavna", "Upitna", "Zapovedna", "Uzvična"], answer: 2 },
  { id: "s064", subject: "Srpski jezik", question: "Suprotno od 'dolaziti' je?", options: ["Trčati", "Odlaziti", "Sedeti", "Stajati"], answer: 1 },
  { id: "s065", subject: "Srpski jezik", question: "Koje slovo je samoglasnik: B, D, E, G?", options: ["B", "D", "E", "G"], answer: 2 },
  { id: "s066", subject: "Srpski jezik", question: "Reč 'sunce' je kojeg roda?", options: ["Muškog", "Ženskog", "Srednjeg", "Promenljivog"], answer: 2 },
  { id: "s067", subject: "Srpski jezik", question: "Koliko slogova ima reč 'računar'?", options: ["2", "4", "3", "5"], answer: 2 },
  { id: "s068", subject: "Srpski jezik", question: "Ko je skupio i zapisao srpske narodne priče i pesme?", options: ["Dositej Obradović", "Jovan Jovanović Zmaj", "Vuk Stefanović Karadžić", "Branko Radičević"], answer: 2 },
  { id: "s069", subject: "Srpski jezik", question: "Reč 'pesnik' označava?", options: ["Predmet", "Osobinu", "Biće", "Radnju"], answer: 2 },
  { id: "s070", subject: "Srpski jezik", question: "Glagol 'trčao je' je u kom vremenu?", options: ["Sadašnjem", "Budućem", "Prošlom", "Imperativu"], answer: 2 },
  { id: "s071", subject: "Srpski jezik", question: "Pridev opisuje?", options: ["Radnju", "Imenicu", "Glagol", "Veznik"], answer: 1 },
  { id: "s072", subject: "Srpski jezik", question: "Koje slovo je suglasnik: A, O, M, E?", options: ["A", "O", "M", "E"], answer: 2 },
  { id: "s073", subject: "Srpski jezik", question: "Reč 'hladan' u ženskom rodu je?", options: ["hladno", "hladni", "hladna", "hladnih"], answer: 2 },
  { id: "s074", subject: "Srpski jezik", question: "Pesmu za decu 'Plavi zec' napisao je?", options: ["Vuk Karadžić", "Jovan Jovanović Zmaj", "Desanka Maksimović", "Branko Ćopić"], answer: 3 },
  { id: "s075", subject: "Srpski jezik", question: "Reč 'učenik' u množini je?", options: ["učenici", "učenikovi", "učenika", "učeničke"], answer: 0 },
  { id: "s076", subject: "Srpski jezik", question: "Koja vrsta reči kazuje šta neko radi?", options: ["Imenica", "Pridev", "Glagol", "Prilog"], answer: 2 },
  { id: "s077", subject: "Srpski jezik", question: "Reč 'ptica' je kojeg roda?", options: ["Muškog", "Ženskog", "Srednjeg", "Zajedničkog"], answer: 1 },
  { id: "s078", subject: "Srpski jezik", question: "Suprotno od 'pametan' je?", options: ["Lud", "Glup", "Tup", "Nespaman"], answer: 1 },
  { id: "s079", subject: "Srpski jezik", question: "Koliko slogova ima reč 'prozor'?", options: ["1", "3", "2", "4"], answer: 2 },
  { id: "s080", subject: "Srpski jezik", question: "Koja reč označava osobinu: trčati, zeleno, bežati, noga?", options: ["trčati", "zeleno", "bežati", "noga"], answer: 1 },
  { id: "s081", subject: "Srpski jezik", question: "Reč 'jutro' je imenica kojeg roda?", options: ["Muškog", "Ženskog", "Srednjeg", "Opšteg"], answer: 2 },
  { id: "s082", subject: "Srpski jezik", question: "Koja rečenica sadrži pridev?", options: ["Dečak trči.", "Visoki dečak trči.", "Dečak trči brzo.", "Dečak i devojčica trče."], answer: 1 },
  { id: "s083", subject: "Srpski jezik", question: "Reč 'raditi' je?", options: ["Imenica", "Pridev", "Glagol u infinitivu", "Prilog"], answer: 2 },
  { id: "s084", subject: "Srpski jezik", question: "Koliko slova ima reč 'jelen'?", options: ["4", "6", "5", "3"], answer: 2 },
  { id: "s085", subject: "Srpski jezik", question: "Reč 'brzo' opisuje?", options: ["Imenicu", "Glagol", "Pridev", "Drugu imenicu"], answer: 1 },
  { id: "s086", subject: "Srpski jezik", question: "Rečenica 'Pada kiša.' je?", options: ["Upitna", "Zapovedna", "Izjavna", "Uzvična"], answer: 2 },
  { id: "s087", subject: "Srpski jezik", question: "Koja reč je homonim za 'luk' (povrće / oružje)?", options: ["Nema homonima", "Luk", "Luka", "Lukov"], answer: 1 },
  { id: "s088", subject: "Srpski jezik", question: "Imenica 'more' je kojeg roda?", options: ["Muškog", "Ženskog", "Srednjeg", "Zajedničkog"], answer: 2 },
  { id: "s089", subject: "Srpski jezik", question: "Koliko slogova ima reč 'biblioteka'?", options: ["3", "5", "4", "6"], answer: 1 },
  { id: "s090", subject: "Srpski jezik", question: "Prilog za vreme odgovara na pitanje?", options: ["Kako?", "Gde?", "Kada?", "Zašto?"], answer: 2 },
  { id: "s091", subject: "Srpski jezik", question: "Reč 'vetar' u množini je?", options: ["vetrovi", "vetrevi", "vetri", "vetrova"], answer: 0 },
  { id: "s092", subject: "Srpski jezik", question: "Suprotno od 'otvoriti' je?", options: ["Pomeriti", "Zatvoriti", "Skinuti", "Gurnuti"], answer: 1 },
  { id: "s093", subject: "Srpski jezik", question: "Koja slova se pišu velikim slovom?", options: ["Sva slova u rečenici", "Samo lična imenа", "Prva reč u rečenici i vlastita imenа", "Samo glagoli"], answer: 2 },
  { id: "s094", subject: "Srpski jezik", question: "Reč 'sestra' je kojeg roda?", options: ["Muškog", "Ženskog", "Srednjeg", "Zajedničkog"], answer: 1 },
  { id: "s095", subject: "Srpski jezik", question: "Koji je sinonim za 'lice'?", options: ["Vrat", "Obraz", "Čelo", "Obličje"], answer: 3 },
  { id: "s096", subject: "Srpski jezik", question: "Koliko slova ima reč 'čokolada'?", options: ["7", "9", "8", "10"], answer: 2 },
  { id: "s097", subject: "Srpski jezik", question: "Reč 'pevač' označava?", options: ["Radnju", "Osobinu", "Biće", "Predmet"], answer: 2 },
  { id: "s098", subject: "Srpski jezik", question: "Glagol 'jedem' je u?", options: ["Prošlom vremenu", "Budućem vremenu", "Sadašnjem vremenu", "Imperativu"], answer: 2 },
  { id: "s099", subject: "Srpski jezik", question: "Reč 'drvo' u množini je?", options: ["Drvovi", "Drvlje", "Drveta", "Drva"], answer: 3 },
  { id: "s100", subject: "Srpski jezik", question: "Prilog za mesto odgovara na pitanje?", options: ["Kada?", "Kako?", "Gde?", "Koliko?"], answer: 2 },

  // ── PRIRODA I DRUŠTVO ───────────────────────────────────
  { id: "p001", subject: "Priroda i društvo", question: "Koliko kontinenata ima na Zemlji?", options: ["5", "6", "7", "8"], answer: 2 },
  { id: "p002", subject: "Priroda i društvo", question: "Koji je glavni grad Srbije?", options: ["Novi Sad", "Niš", "Beograd", "Kragujevac"], answer: 2 },
  { id: "p003", subject: "Priroda i društvo", question: "Reka koja protiče kroz Beograd je?", options: ["Morava", "Drina", "Dunav", "Nišava"], answer: 2 },
  { id: "p004", subject: "Priroda i društvo", question: "Koliko meseci ima godina?", options: ["10", "11", "12", "13"], answer: 2 },
  { id: "p005", subject: "Priroda i društvo", question: "Koji mesec ima 28 ili 29 dana?", options: ["Januar", "Februar", "Mart", "April"], answer: 1 },
  { id: "p006", subject: "Priroda i društvo", question: "Kojoj grupi živih bića pripada ptica?", options: ["Sisari", "Gmizavci", "Ptice", "Ribe"], answer: 2 },
  { id: "p007", subject: "Priroda i društvo", question: "Šta biljkama treba za fotosintezu?", options: ["Meso i voda", "Sunčeva svetlost, voda i CO₂", "Kiseonik i šećer", "Zemlja i vetar"], answer: 1 },
  { id: "p008", subject: "Priroda i društvo", question: "Koja planeta je najbliža Suncu?", options: ["Venera", "Zemlja", "Merkur", "Mars"], answer: 2 },
  { id: "p009", subject: "Priroda i društvo", question: "Koliko dana ima jedna sedmica?", options: ["5", "6", "7", "8"], answer: 2 },
  { id: "p010", subject: "Priroda i društvo", question: "Koji organ pumpa krv kroz telo?", options: ["Pluća", "Jetra", "Srce", "Bubreg"], answer: 2 },
  { id: "p011", subject: "Priroda i društvo", question: "Čime dišu ribe?", options: ["Plućima", "Škrgama", "Kožom", "Nosom"], answer: 1 },
  { id: "p012", subject: "Priroda i društvo", question: "Koja je najveća životinja na kopnu?", options: ["Žirafa", "Nilski konj", "Slon", "Nosorog"], answer: 2 },
  { id: "p013", subject: "Priroda i društvo", question: "Koje godišnje doba dolazi posle zime?", options: ["Jesen", "Leto", "Proleće", "Nema promene"], answer: 2 },
  { id: "p014", subject: "Priroda i društvo", question: "Od čega se najčešće pravi hleb?", options: ["Kukuruza", "Pirinča", "Pšeničnog brašna", "Ječma"], answer: 2 },
  { id: "p015", subject: "Priroda i društvo", question: "Koji gas udišemo, a bez kojeg ne možemo živeti?", options: ["Ugljovodonik", "Azot", "Kiseonik", "Ugljen dioksid"], answer: 2 },
  { id: "p016", subject: "Priroda i društvo", question: "Najduža reka u Srbiji je?", options: ["Sava", "Drina", "Velika Morava", "Dunav u Srbiji"], answer: 2 },
  { id: "p017", subject: "Priroda i društvo", question: "Koji organ koristimo za varenje hrane?", options: ["Srce", "Želudac", "Pluća", "Mozak"], answer: 1 },
  { id: "p018", subject: "Priroda i društvo", question: "Šta je fotosinteza?", options: ["Disanje biljaka", "Stvaranje hrane uz pomoć svetlosti", "Rast biljaka", "Razmnožavanje biljaka"], answer: 1 },
  { id: "p019", subject: "Priroda i društvo", question: "Koliko kostiju ima odrasli čovek (približno)?", options: ["106", "206", "306", "406"], answer: 1 },
  { id: "p020", subject: "Priroda i društvo", question: "Koja životinja je poznata kao 'kralj životinja'?", options: ["Tigar", "Medved", "Lav", "Gepard"], answer: 2 },
  { id: "p021", subject: "Priroda i društvo", question: "Šta se slavi 15. februara u Srbiji?", options: ["Dan škole", "Dan državnosti Srbije", "Dan majki", "Nova godina"], answer: 1 },
  { id: "p022", subject: "Priroda i društvo", question: "Koja strana sveta je suprotna od severa?", options: ["Istok", "Zapad", "Jug", "Severoistok"], answer: 2 },
  { id: "p023", subject: "Priroda i društvo", question: "Kompas pokazuje prema kojoj strani sveta?", options: ["Jugu", "Istoku", "Severu", "Zapadu"], answer: 2 },
  { id: "p024", subject: "Priroda i društvo", question: "Koja je najduža reka na svetu?", options: ["Amazon", "Nil", "Jangce", "Misisipi"], answer: 1 },
  { id: "p025", subject: "Priroda i društvo", question: "Koliko planeta ima u Sunčevom sistemu?", options: ["7", "8", "9", "10"], answer: 1 },
  { id: "p026", subject: "Priroda i društvo", question: "Šta su listopadna stabla?", options: ["Stabla koja rastu brzo", "Stabla koja gube lišće zimi", "Stabla sa četinama", "Stabla koja nikad ne rastu"], answer: 1 },
  { id: "p027", subject: "Priroda i društvo", question: "Ko donosi zakone u Srbiji?", options: ["Predsednik", "Vlada", "Skupština", "Sudovi"], answer: 2 },
  { id: "p028", subject: "Priroda i društvo", question: "Kako se zove naša planeta?", options: ["Mars", "Venera", "Zemlja", "Saturn"], answer: 2 },
  { id: "p029", subject: "Priroda i društvo", question: "Koja životinja ne spava tokom zimskog sna: medved, jež, zec ili puh?", options: ["Medved", "Jež", "Zec", "Puh"], answer: 2 },
  { id: "p030", subject: "Priroda i društvo", question: "Gde žive pingvini?", options: ["Na Arktiku", "U Africi", "Na Antarktiku", "U Aziji"], answer: 2 },
  { id: "p031", subject: "Priroda i društvo", question: "Koliko godišnjih doba ima?", options: ["2", "3", "4", "5"], answer: 2 },
  { id: "p032", subject: "Priroda i društvo", question: "Koja je prestonica Francuske?", options: ["Rim", "Berlin", "Pariz", "Madrid"], answer: 2 },
  { id: "p033", subject: "Priroda i društvo", question: "Koji je najveći okean na svetu?", options: ["Atlantski", "Indijski", "Tihi", "Arktički"], answer: 2 },
  { id: "p034", subject: "Priroda i društvo", question: "Od čega je sastavljen vazduh koji dišemo?", options: ["Samo kiseonik", "Samo azot", "Mešavina gasova", "Samo ugljen dioksid"], answer: 2 },
  { id: "p035", subject: "Priroda i društvo", question: "Koja životinja daje mleko i hrani mladunče?", options: ["Orao", "Žaba", "Krava", "Zmija"], answer: 2 },
  { id: "p036", subject: "Priroda i društvo", question: "Koji organ čistí krv u telu?", options: ["Srce", "Pluća", "Bubrezi", "Želudac"], answer: 2 },
  { id: "p037", subject: "Priroda i društvo", question: "Kako se zove naša galaksija?", options: ["Andromeda", "Mlečni put", "Orion", "Magelanov oblak"], answer: 1 },
  { id: "p038", subject: "Priroda i društvo", question: "Koja je glavna uloga lista na biljci?", options: ["Upijanje vode", "Fotosinteza", "Razmnožavanje", "Zaštita"], answer: 1 },
  { id: "p039", subject: "Priroda i društvo", question: "Šta je geograf?", options: ["Naučnik koji proučava zvezde", "Naučnik koji proučava Zemlju", "Naučnik koji proučava ribe", "Naučnik koji proučava insekte"], answer: 1 },
  { id: "p040", subject: "Priroda i društvo", question: "Koji dan je prvi radni dan u nedelji?", options: ["Subota", "Nedelja", "Ponedeljak", "Utorak"], answer: 2 },
  { id: "p041", subject: "Priroda i društvo", question: "Koja od ovih životinja je biljojed?", options: ["Lav", "Vuk", "Krava", "Orao"], answer: 2 },
  { id: "p042", subject: "Priroda i društvo", question: "Koja je najduža planinska kosa u Srbiji?", options: ["Kopaonik", "Tara", "Stara planina", "Zlatibor"], answer: 0 },
  { id: "p043", subject: "Priroda i društvo", question: "Koja reka protiče kroz Novi Sad?", options: ["Sava", "Morava", "Dunav", "Tisa"], answer: 2 },
  { id: "p044", subject: "Priroda i društvo", question: "Šta je ekosistem?", options: ["Vrsta biljke", "Zajednica živih bića i njihovog staništa", "Vrsta stene", "Deo atmosfere"], answer: 1 },
  { id: "p045", subject: "Priroda i društvo", question: "Koji mesec je sedmi u godini?", options: ["Jun", "Avgust", "Juli", "Septembar"], answer: 2 },
  { id: "p046", subject: "Priroda i društvo", question: "Koja je prestonica Nemačke?", options: ["Minhen", "Hamburg", "Frankfurt", "Berlin"], answer: 3 },
  { id: "p047", subject: "Priroda i društvo", question: "Čega ima najviše na površini Zemlje?", options: ["Kopna", "Leda", "Vode", "Peska"], answer: 2 },
  { id: "p048", subject: "Priroda i društvo", question: "Koja životinja je najbrža na svetu?", options: ["Lav", "Gepard", "Konj", "Antilopa"], answer: 1 },
  { id: "p049", subject: "Priroda i društvo", question: "Šta su prerije?", options: ["Ledene planine", "Prostrana travnata područja", "Tropske šume", "Pustinjska područja"], answer: 1 },
  { id: "p050", subject: "Priroda i društvo", question: "Koja planeta je najudaljenija od Sunca?", options: ["Saturn", "Uran", "Jupiter", "Neptun"], answer: 3 },
  { id: "p051", subject: "Priroda i društvo", question: "Koji je hemijski simbol za vodu?", options: ["CO₂", "O₂", "H₂O", "NaCl"], answer: 2 },
  { id: "p052", subject: "Priroda i društvo", question: "Koja je prestonica Italije?", options: ["Venecija", "Milano", "Napulj", "Rim"], answer: 3 },
  { id: "p053", subject: "Priroda i društvo", question: "Šta je vulkan?", options: ["Vrsta jezera", "Planina iz koje izbija magma", "Vrsta oblaka", "Duboka jama u moru"], answer: 1 },
  { id: "p054", subject: "Priroda i društvo", question: "Koji organ je odgovoran za razmenu gasova u telu?", options: ["Srce", "Jetra", "Pluća", "Bubrezi"], answer: 2 },
  { id: "p055", subject: "Priroda i društvo", question: "Šta je migracija ptica?", options: ["Ptica koja peva", "Sezonsko preseljenje ptica", "Vrsta gnezda", "Ishrana ptica"], answer: 1 },
  { id: "p056", subject: "Priroda i društvo", question: "Koji kontinent je najveći na svetu?", options: ["Amerika", "Afrika", "Azija", "Evropa"], answer: 2 },
  { id: "p057", subject: "Priroda i društvo", question: "Koja je uloga korena biljke?", options: ["Fotosinteza", "Upijanje vode i minerala iz zemlje", "Razmnožavanje", "Isparavanje"], answer: 1 },
  { id: "p058", subject: "Priroda i društvo", question: "Šta je zemljotres?", options: ["Jak vetar", "Potresanje Zemljine površine", "Vrsta poplave", "Vulkanska erupcija"], answer: 1 },
  { id: "p059", subject: "Priroda i društvo", question: "Koji mesec je poslednji u godini?", options: ["Novembar", "Januar", "Decembar", "Oktobar"], answer: 2 },
  { id: "p060", subject: "Priroda i društvo", question: "Koja životinja gradi branu od stabala?", options: ["Vidra", "Dabar", "Puh", "Jazavac"], answer: 1 },
  { id: "p061", subject: "Priroda i društvo", question: "Šta je atmosfera?", options: ["Unutrašnjost Zemlje", "Sloj vazduha oko Zemlje", "Površina mora", "Vrsta stene"], answer: 1 },
  { id: "p062", subject: "Priroda i društvo", question: "Koja je najduža reka u Evropi?", options: ["Dunav", "Rajna", "Volga", "Temza"], answer: 2 },
  { id: "p063", subject: "Priroda i društvo", question: "Koji deo tela štiti mozak?", options: ["Rebra", "Kičma", "Lobanja", "Vilica"], answer: 2 },
  { id: "p064", subject: "Priroda i društvo", question: "Šta je savana?", options: ["Hladna šuma", "Tropska travnata površina sa retkim drvećem", "Pustinja", "Planinski vrh"], answer: 1 },
  { id: "p065", subject: "Priroda i društvo", question: "Koja zemlja je najveća na svetu po površini?", options: ["Kina", "SAD", "Rusija", "Kanada"], answer: 2 },
  { id: "p066", subject: "Priroda i društvo", question: "Šta je reciklaža?", options: ["Bacanje otpada", "Ponovna upotreba materijala", "Spaljivanje smeća", "Kopanje ruda"], answer: 1 },
  { id: "p067", subject: "Priroda i društvo", question: "Koji organ proizvodi žuč?", options: ["Bubreg", "Pankreas", "Jetra", "Srce"], answer: 2 },
  { id: "p068", subject: "Priroda i društvo", question: "Šta je erozija?", options: ["Rast biljaka", "Razaranje tla vodom ili vetrom", "Vrsta minerala", "Stvaranje oblaka"], answer: 1 },
  { id: "p069", subject: "Priroda i društvo", question: "Koja je prestonica Španije?", options: ["Barselona", "Sevilja", "Madrid", "Valensija"], answer: 2 },
  { id: "p070", subject: "Priroda i društvo", question: "Koji insekt proizvodi med?", options: ["Muva", "Pčela", "Mrav", "Leptir"], answer: 1 },
  { id: "p071", subject: "Priroda i društvo", question: "Šta je cirkulacija krvi?", options: ["Disanje", "Kretanje krvi kroz telo", "Varenje hrane", "Rad mišića"], answer: 1 },
  { id: "p072", subject: "Priroda i društvo", question: "Koja planina je najviša u Srbiji?", options: ["Zlatibor", "Tara", "Kopaonik", "Stara planina"], answer: 2 },
  { id: "p073", subject: "Priroda i društvo", question: "Koja životinja je simbol mira?", options: ["Orao", "Golub", "Vrabac", "Lastavica"], answer: 1 },
  { id: "p074", subject: "Priroda i društvo", question: "Šta je prognoza vremena?", options: ["Merenje temperature", "Predviđanje budućeg vremena", "Merenje vlažnosti", "Snimanje oblaka"], answer: 1 },
  { id: "p075", subject: "Priroda i društvo", question: "Koji mesec je prvi u godini?", options: ["Mart", "Februar", "Januar", "April"], answer: 2 },
  { id: "p076", subject: "Priroda i društvo", question: "Šta su četinari?", options: ["Biljke sa cvetovima", "Biljke sa iglicama i šiškama", "Biljke koje rastu u vodi", "Biljke bez listova"], answer: 1 },
  { id: "p077", subject: "Priroda i društvo", question: "Koji organ čoveka raste tokom celog života?", options: ["Srce", "Mozak", "Nos", "Pluća"], answer: 2 },
  { id: "p078", subject: "Priroda i društvo", question: "Šta je poplava?", options: ["Suša", "Jak vetar", "Izlivanje vode iz reke", "Potres tla"], answer: 2 },
  { id: "p079", subject: "Priroda i društvo", question: "Koja je prestonica Rusije?", options: ["Sankt Peterburg", "Kijev", "Moskva", "Minsk"], answer: 2 },
  { id: "p080", subject: "Priroda i društvo", question: "Šta je stablo biljke?", options: ["Koren biljke", "Centralni deo koji nosi granje i lišće", "Cvet biljke", "Plod biljke"], answer: 1 },
  { id: "p081", subject: "Priroda i društvo", question: "Koja je osnovna jedinica naslednosti?", options: ["Atom", "Ćelija", "Gen", "Molekul"], answer: 2 },
  { id: "p082", subject: "Priroda i društvo", question: "Šta je suša?", options: ["Previše kiše", "Duži period bez kiše", "Jak vetar", "Snežna oluja"], answer: 1 },
  { id: "p083", subject: "Priroda i društvo", question: "Koliko oktopodsа ima krakova?", options: ["6", "10", "8", "12"], answer: 2 },
  { id: "p084", subject: "Priroda i društvo", question: "Koja reka se uliva u Crno more?", options: ["Sava", "Drina", "Dunav", "Morava"], answer: 2 },
  { id: "p085", subject: "Priroda i društvo", question: "Koji deo biljke upija sunčevu svetlost?", options: ["Koren", "Stablo", "List", "Plod"], answer: 2 },
  { id: "p086", subject: "Priroda i društvo", question: "Koja životinja može da živi i na kopnu i u vodi?", options: ["Krokodil", "Orao", "Pas", "Lav"], answer: 0 },
  { id: "p087", subject: "Priroda i društvo", question: "Kako se zove čovek koji upravlja državom u Srbiji?", options: ["Kralj", "Predsednik", "Premijer", "Gradonačelnik"], answer: 1 },
  { id: "p088", subject: "Priroda i društvo", question: "Šta je herbivora?", options: ["Životinja koja jede meso", "Biljojed", "Svaštojed", "Insektojed"], answer: 1 },
  { id: "p089", subject: "Priroda i društvo", question: "Koji kontinent je najmanji?", options: ["Evropa", "Australija", "Antarktik", "Južna Amerika"], answer: 1 },
  { id: "p090", subject: "Priroda i društvo", question: "Šta je termometar?", options: ["Sprava za merenje pritiska", "Sprava za merenje temperature", "Sprava za merenje vlage", "Sprava za merenje vetra"], answer: 1 },
  { id: "p091", subject: "Priroda i društvo", question: "Koji je najmanji kontinent?", options: ["Antarktik", "Evropa", "Australija", "Južna Amerika"], answer: 2 },
  { id: "p092", subject: "Priroda i društvo", question: "Šta je poluostrvo?", options: ["Kopno okruženo vodom sa svih strana", "Kopno okruženo vodom sa tri strane", "Ostrvo u reci", "Deo dna mora"], answer: 1 },
  { id: "p093", subject: "Priroda i društvo", question: "Koja biljka 'jede' insekte?", options: ["Kaktus", "Venerin lončić", "Orhideja", "Paprat"], answer: 1 },
  { id: "p094", subject: "Priroda i društvo", question: "Šta je nafta?", options: ["Vrsta mineralne vode", "Prirodno tečno gorivo iz Zemljinih dubina", "Hemijska supstanca", "Vrsta uglja"], answer: 1 },
  { id: "p095", subject: "Priroda i društvo", question: "Koji deo tela čoveka sadrži najviše kostiju?", options: ["Ruka", "Noga", "Šaka", "Stopalo"], answer: 2 },
  { id: "p096", subject: "Priroda i društvo", question: "Koja je prestonica Grčke?", options: ["Solun", "Atina", "Krit", "Patra"], answer: 1 },
  { id: "p097", subject: "Priroda i društvo", question: "Šta je ozon?", options: ["Vrsta metala", "Gas koji štiti Zemlju od UV zraka", "Vrsta kiseline", "Zagađivač"], answer: 1 },
  { id: "p098", subject: "Priroda i društvo", question: "Koliko komora ima srce čoveka?", options: ["2", "3", "4", "5"], answer: 2 },
  { id: "p099", subject: "Priroda i društvo", question: "Šta je potrošačko društvo?", options: ["Društvo koje reciklira", "Društvo koje troši više nego što je potrebno", "Siromašno društvo", "Ruralno društvo"], answer: 1 },
  { id: "p100", subject: "Priroda i društvo", question: "Koji organ kontroliše sve funkcije tela?", options: ["Srce", "Pluća", "Mozak", "Jetra"], answer: 2 },

  // ── NEMAČKI JEZIK ────────────────────────────────────────
  { id: "n001", subject: "Nemački jezik", question: "Kako se kaže 'dobar dan' na nemačkom?", options: ["Guten Abend", "Guten Morgen", "Guten Tag", "Auf Wiedersehen"], answer: 2 },
  { id: "n002", subject: "Nemački jezik", question: "Kako se kaže 'hvala' na nemačkom?", options: ["Bitte", "Danke", "Entschuldigung", "Hallo"], answer: 1 },
  { id: "n003", subject: "Nemački jezik", question: "Kako se kaže 'jedan' na nemačkom?", options: ["Zwei", "Drei", "Eins", "Vier"], answer: 2 },
  { id: "n004", subject: "Nemački jezik", question: "Kako se kaže 'škola' na nemačkom?", options: ["Haus", "Schule", "Buch", "Tisch"], answer: 1 },
  { id: "n005", subject: "Nemački jezik", question: "Kako se kaže 'pas' na nemačkom?", options: ["Katze", "Maus", "Hund", "Vogel"], answer: 2 },
  { id: "n006", subject: "Nemački jezik", question: "Kako se kaže 'mačka' na nemačkom?", options: ["Hund", "Katze", "Fisch", "Pferd"], answer: 1 },
  { id: "n007", subject: "Nemački jezik", question: "Kako se kaže 'jabuka' na nemačkom?", options: ["Birne", "Banane", "Apfel", "Orange"], answer: 2 },
  { id: "n008", subject: "Nemački jezik", question: "Kako se kaže 'majka' na nemačkom?", options: ["Vater", "Bruder", "Mutter", "Schwester"], answer: 2 },
  { id: "n009", subject: "Nemački jezik", question: "Kako se kaže 'otac' na nemačkom?", options: ["Mutter", "Vater", "Sohn", "Onkel"], answer: 1 },
  { id: "n010", subject: "Nemački jezik", question: "Kako se kaže 'dobro jutro' na nemačkom?", options: ["Guten Tag", "Gute Nacht", "Guten Morgen", "Hallo"], answer: 2 },
  { id: "n011", subject: "Nemački jezik", question: "Kako se kaže 'laku noć' na nemačkom?", options: ["Guten Morgen", "Gute Nacht", "Guten Abend", "Tschüss"], answer: 1 },
  { id: "n012", subject: "Nemački jezik", question: "Kako se kaže 'knjiga' na nemačkom?", options: ["Heft", "Stift", "Buch", "Tafel"], answer: 2 },
  { id: "n013", subject: "Nemački jezik", question: "Kako se kaže 'dva' na nemačkom?", options: ["Eins", "Drei", "Zwei", "Vier"], answer: 2 },
  { id: "n014", subject: "Nemački jezik", question: "Kako se kaže 'deset' na nemačkom?", options: ["Acht", "Neun", "Zehn", "Sieben"], answer: 2 },
  { id: "n015", subject: "Nemački jezik", question: "Kako se kaže 'crvena' na nemačkom?", options: ["Blau", "Grün", "Rot", "Gelb"], answer: 2 },
  { id: "n016", subject: "Nemački jezik", question: "Kako se kaže 'plava' na nemačkom?", options: ["Rot", "Blau", "Grün", "Weiß"], answer: 1 },
  { id: "n017", subject: "Nemački jezik", question: "Kako se kaže 'kuća' na nemačkom?", options: ["Auto", "Haus", "Baum", "Blume"], answer: 1 },
  { id: "n018", subject: "Nemački jezik", question: "Kako se kaže 'drvo' na nemačkom?", options: ["Blume", "Gras", "Baum", "Stein"], answer: 2 },
  { id: "n019", subject: "Nemački jezik", question: "Kako se kaže 'prijatelj' na nemačkom?", options: ["Feind", "Freund", "Lehrer", "Schüler"], answer: 1 },
  { id: "n020", subject: "Nemački jezik", question: "Kako se kaže 'učiteljica' na nemačkom?", options: ["Schülerin", "Mutter", "Lehrerin", "Freundin"], answer: 2 },
  { id: "n021", subject: "Nemački jezik", question: "Kako se kaže 'zelena' na nemačkom?", options: ["Rot", "Blau", "Grün", "Schwarz"], answer: 2 },
  { id: "n022", subject: "Nemački jezik", question: "Šta znači reč 'Wasser'?", options: ["Vatра", "Vazduh", "Voda", "Zemlja"], answer: 2 },
  { id: "n023", subject: "Nemački jezik", question: "Šta znači reč 'Brot'?", options: ["Mleko", "Hleb", "Sir", "Meso"], answer: 1 },
  { id: "n024", subject: "Nemački jezik", question: "Kako se kaže 'doviđenja' na nemačkom?", options: ["Hallo", "Danke", "Auf Wiedersehen", "Bitte"], answer: 2 },
  { id: "n025", subject: "Nemački jezik", question: "Šta znači reč 'Schule'?", options: ["Igra", "Škola", "Kuća", "Knjiga"], answer: 1 },
  { id: "n026", subject: "Nemački jezik", question: "Kako se kaže 'pet' na nemačkom?", options: ["Vier", "Sechs", "Fünf", "Drei"], answer: 2 },
  { id: "n027", subject: "Nemački jezik", question: "Šta znači 'Ich heiße...'?", options: ["Imam ... godina", "Ja se zovem...", "Ja sam iz...", "Ja volim..."], answer: 1 },
  { id: "n028", subject: "Nemački jezik", question: "Šta znači 'Wie alt bist du?'?", options: ["Kako se zoveš?", "Odakle si?", "Koliko imaš godina?", "Gde živiš?"], answer: 2 },
  { id: "n029", subject: "Nemački jezik", question: "Kako se kaže 'sveska' na nemačkom?", options: ["Buch", "Heft", "Stift", "Lineal"], answer: 1 },
  { id: "n030", subject: "Nemački jezik", question: "Šta znači 'Ich verstehe nicht'?", options: ["Razumem", "Ne čujem", "Ne razumem", "Ne znam"], answer: 2 },
  { id: "n031", subject: "Nemački jezik", question: "Kako se kaže 'šest' na nemačkom?", options: ["Fünf", "Sieben", "Sechs", "Acht"], answer: 2 },
  { id: "n032", subject: "Nemački jezik", question: "Kako se kaže 'sedam' na nemačkom?", options: ["Sechs", "Acht", "Sieben", "Neun"], answer: 2 },
  { id: "n033", subject: "Nemački jezik", question: "Kako se kaže 'osam' na nemačkom?", options: ["Sieben", "Neun", "Acht", "Zehn"], answer: 2 },
  { id: "n034", subject: "Nemački jezik", question: "Kako se kaže 'devet' na nemačkom?", options: ["Acht", "Zehn", "Neun", "Sieben"], answer: 2 },
  { id: "n035", subject: "Nemački jezik", question: "Kako se kaže 'tri' na nemačkom?", options: ["Eins", "Zwei", "Drei", "Vier"], answer: 2 },
  { id: "n036", subject: "Nemački jezik", question: "Kako se kaže 'četiri' na nemačkom?", options: ["Drei", "Fünf", "Vier", "Sechs"], answer: 2 },
  { id: "n037", subject: "Nemački jezik", question: "Šta znači reč 'Hund'?", options: ["Mačka", "Konj", "Pas", "Ptica"], answer: 2 },
  { id: "n038", subject: "Nemački jezik", question: "Šta znači reč 'Katze'?", options: ["Pas", "Mačka", "Miš", "Zec"], answer: 1 },
  { id: "n039", subject: "Nemački jezik", question: "Kako se kaže 'žuta' na nemačkom?", options: ["Rot", "Blau", "Grün", "Gelb"], answer: 3 },
  { id: "n040", subject: "Nemački jezik", question: "Kako se kaže 'bela' na nemačkom?", options: ["Schwarz", "Weiß", "Grau", "Braun"], answer: 1 },
  { id: "n041", subject: "Nemački jezik", question: "Kako se kaže 'crna' na nemačkom?", options: ["Weiß", "Grau", "Schwarz", "Braun"], answer: 2 },
  { id: "n042", subject: "Nemački jezik", question: "Šta znači reč 'Apfel'?", options: ["Kruška", "Banana", "Jabuka", "Narandža"], answer: 2 },
  { id: "n043", subject: "Nemački jezik", question: "Šta znači reč 'Banane'?", options: ["Jabuka", "Banana", "Šljiva", "Grožđe"], answer: 1 },
  { id: "n044", subject: "Nemački jezik", question: "Kako se kaže 'sestra' na nemačkom?", options: ["Bruder", "Mutter", "Schwester", "Tante"], answer: 2 },
  { id: "n045", subject: "Nemački jezik", question: "Kako se kaže 'brat' na nemačkom?", options: ["Schwester", "Vater", "Bruder", "Onkel"], answer: 2 },
  { id: "n046", subject: "Nemački jezik", question: "Šta znači reč 'Haus'?", options: ["Stan", "Škola", "Kuća", "Dvorac"], answer: 2 },
  { id: "n047", subject: "Nemački jezik", question: "Šta znači reč 'Baum'?", options: ["Cvet", "Trava", "Drvo", "Grm"], answer: 2 },
  { id: "n048", subject: "Nemački jezik", question: "Kako se kaže 'meso' na nemačkom?", options: ["Fisch", "Brot", "Fleisch", "Käse"], answer: 2 },
  { id: "n049", subject: "Nemački jezik", question: "Kako se kaže 'mleko' na nemačkom?", options: ["Wasser", "Saft", "Milch", "Tee"], answer: 2 },
  { id: "n050", subject: "Nemački jezik", question: "Šta znači reč 'Milch'?", options: ["Sok", "Voda", "Mleko", "Čaj"], answer: 2 },
  { id: "n051", subject: "Nemački jezik", question: "Šta znači reč 'Buch'?", options: ["Sveska", "Olovka", "Knjiga", "Tabla"], answer: 2 },
  { id: "n052", subject: "Nemački jezik", question: "Kako se kaže 'olovka' na nemačkom?", options: ["Buch", "Heft", "Stift", "Lineal"], answer: 2 },
  { id: "n053", subject: "Nemački jezik", question: "Kako se kaže 'lenjir' na nemačkom?", options: ["Stift", "Heft", "Buch", "Lineal"], answer: 3 },
  { id: "n054", subject: "Nemački jezik", question: "Šta znači 'Guten Morgen'?", options: ["Dobro veče", "Laku noć", "Dobro jutro", "Dobar dan"], answer: 2 },
  { id: "n055", subject: "Nemački jezik", question: "Šta znači 'Guten Abend'?", options: ["Dobro jutro", "Dobar dan", "Dobro veče", "Laku noć"], answer: 2 },
  { id: "n056", subject: "Nemački jezik", question: "Šta znači 'Gute Nacht'?", options: ["Dobar dan", "Dobro jutro", "Dobro veče", "Laku noć"], answer: 3 },
  { id: "n057", subject: "Nemački jezik", question: "Kako se kaže 'auto' na nemačkom?", options: ["Zug", "Bus", "Auto", "Fahrrad"], answer: 2 },
  { id: "n058", subject: "Nemački jezik", question: "Kako se kaže 'voz' na nemačkom?", options: ["Auto", "Bus", "Zug", "Flugzeug"], answer: 2 },
  { id: "n059", subject: "Nemački jezik", question: "Kako se kaže 'avion' na nemačkom?", options: ["Zug", "Schiff", "Bus", "Flugzeug"], answer: 3 },
  { id: "n060", subject: "Nemački jezik", question: "Šta znači 'Wie heißt du?'?", options: ["Kako si?", "Kako se zoveš?", "Odakle si?", "Koliko imaš godina?"], answer: 1 },
  { id: "n061", subject: "Nemački jezik", question: "Šta znači 'Ich bin...'?", options: ["Ja imam...", "Ja idem...", "Ja sam...", "Ja volim..."], answer: 2 },
  { id: "n062", subject: "Nemački jezik", question: "Šta znači 'Wo wohnst du?'?", options: ["Kako se zoveš?", "Koliko imaš godina?", "Gde živiš?", "Odakle si?"], answer: 2 },
  { id: "n063", subject: "Nemački jezik", question: "Kako se kaže 'hleb' na nemačkom?", options: ["Käse", "Milch", "Brot", "Butter"], answer: 2 },
  { id: "n064", subject: "Nemački jezik", question: "Kako se kaže 'sir' na nemačkom?", options: ["Butter", "Brot", "Käse", "Ei"], answer: 2 },
  { id: "n065", subject: "Nemački jezik", question: "Kako se kaže 'jaje' na nemačkom?", options: ["Milch", "Käse", "Brot", "Ei"], answer: 3 },
  { id: "n066", subject: "Nemački jezik", question: "Šta znači reč 'Fisch'?", options: ["Meso", "Riba", "Sir", "Hleb"], answer: 1 },
  { id: "n067", subject: "Nemački jezik", question: "Kako se kaže 'reka' na nemačkom?", options: ["See", "Meer", "Fluss", "Berg"], answer: 2 },
  { id: "n068", subject: "Nemački jezik", question: "Kako se kaže 'planina' na nemačkom?", options: ["Fluss", "See", "Tal", "Berg"], answer: 3 },
  { id: "n069", subject: "Nemački jezik", question: "Šta znači reč 'Blume'?", options: ["Drvo", "Trava", "Cvet", "List"], answer: 2 },
  { id: "n070", subject: "Nemački jezik", question: "Kako se kaže 'dete' na nemačkom?", options: ["Mann", "Frau", "Kind", "Baby"], answer: 2 },
  { id: "n071", subject: "Nemački jezik", question: "Kako se kaže 'igrati se' na nemačkom?", options: ["lernen", "lesen", "spielen", "schreiben"], answer: 2 },
  { id: "n072", subject: "Nemački jezik", question: "Kako se kaže 'učiti' na nemačkom?", options: ["spielen", "schreiben", "lesen", "lernen"], answer: 3 },
  { id: "n073", subject: "Nemački jezik", question: "Kako se kaže 'pisati' na nemačkom?", options: ["lesen", "lernen", "schreiben", "spielen"], answer: 2 },
  { id: "n074", subject: "Nemački jezik", question: "Kako se kaže 'čitati' na nemačkom?", options: ["schreiben", "lernen", "spielen", "lesen"], answer: 3 },
  { id: "n075", subject: "Nemački jezik", question: "Šta znači 'Ich lerne Deutsch'?", options: ["Volim nemački", "Učim nemački", "Govorim nemački", "Čitam nemački"], answer: 1 },
  { id: "n076", subject: "Nemački jezik", question: "Kako se kaže 'sunce' na nemačkom?", options: ["Mond", "Stern", "Sonne", "Wolke"], answer: 2 },
  { id: "n077", subject: "Nemački jezik", question: "Kako se kaže 'mesec' na nemačkom?", options: ["Sonne", "Stern", "Mond", "Wolke"], answer: 2 },
  { id: "n078", subject: "Nemački jezik", question: "Kako se kaže 'zvezda' na nemačkom?", options: ["Sonne", "Mond", "Wolke", "Stern"], answer: 3 },
  { id: "n079", subject: "Nemački jezik", question: "Šta znači reč 'Schüler'?", options: ["Učitelj", "Direktor", "Učenik", "Roditelj"], answer: 2 },
  { id: "n080", subject: "Nemački jezik", question: "Kako se kaže 'konj' na nemačkom?", options: ["Hund", "Katze", "Pferd", "Kuh"], answer: 2 },
  { id: "n081", subject: "Nemački jezik", question: "Kako se kaže 'krava' na nemačkom?", options: ["Pferd", "Schwein", "Kuh", "Schaf"], answer: 2 },
  { id: "n082", subject: "Nemački jezik", question: "Kako se kaže 'svinja' na nemačkom?", options: ["Kuh", "Schaf", "Schwein", "Hund"], answer: 2 },
  { id: "n083", subject: "Nemački jezik", question: "Šta znači 'Ich habe Hunger'?", options: ["Žedan sam", "Umoran sam", "Gladan sam", "Srećan sam"], answer: 2 },
  { id: "n084", subject: "Nemački jezik", question: "Šta znači 'Ich habe Durst'?", options: ["Gladan sam", "Žedan sam", "Hladno mi je", "Toplo mi je"], answer: 1 },
  { id: "n085", subject: "Nemački jezik", question: "Kako se kaže 'dobar' na nemačkom?", options: ["Schlecht", "Klein", "Gut", "Groß"], answer: 2 },
  { id: "n086", subject: "Nemački jezik", question: "Kako se kaže 'loš' na nemačkom?", options: ["Gut", "Klein", "Schlecht", "Groß"], answer: 2 },
  { id: "n087", subject: "Nemački jezik", question: "Kako se kaže 'veliki' na nemačkom?", options: ["Klein", "Schlecht", "Gut", "Groß"], answer: 3 },
  { id: "n088", subject: "Nemački jezik", question: "Kako se kaže 'mali' na nemačkom?", options: ["Groß", "Gut", "Klein", "Alt"], answer: 2 },
  { id: "n089", subject: "Nemački jezik", question: "Šta znači 'Tschüss'?", options: ["Hvala", "Zdravo (pozdrav)", "Molim", "Izvinite"], answer: 1 },
  { id: "n090", subject: "Nemački jezik", question: "Šta znači reč 'Lehrer'?", options: ["Učenik", "Direktor", "Učitelj", "Roditelj"], answer: 2 },
  { id: "n091", subject: "Nemački jezik", question: "Kako se kaže 'molim' na nemačkom?", options: ["Danke", "Entschuldigung", "Bitte", "Hallo"], answer: 2 },
  { id: "n092", subject: "Nemački jezik", question: "Šta znači 'Entschuldigung'?", options: ["Hvala", "Molim", "Izvinite", "Zdravo"], answer: 2 },
  { id: "n093", subject: "Nemački jezik", question: "Kako se kaže 'igračka' na nemačkom?", options: ["Spiel", "Ball", "Spielzeug", "Puppe"], answer: 2 },
  { id: "n094", subject: "Nemački jezik", question: "Kako se kaže 'lopta' na nemačkom?", options: ["Spielzeug", "Puppe", "Ball", "Auto"], answer: 2 },
  { id: "n095", subject: "Nemački jezik", question: "Šta znači 'Ich mag...'?", options: ["Ja ne volim...", "Ja imam...", "Ja volim / sviđa mi se...", "Ja hoću..."], answer: 2 },
  { id: "n096", subject: "Nemački jezik", question: "Kako se kaže 'škola' na nemačkom (još jednom)?", options: ["Haus", "Buch", "Schule", "Heft"], answer: 2 },
  { id: "n097", subject: "Nemački jezik", question: "Šta znači 'Das ist...'?", options: ["Ovo je...", "Ja sam...", "Tamo je...", "Ovde je..."], answer: 0 },
  { id: "n098", subject: "Nemački jezik", question: "Kako se kaže 'rođendan' na nemačkom?", options: ["Weihnachten", "Ostern", "Geburtstag", "Silvester"], answer: 2 },
  { id: "n099", subject: "Nemački jezik", question: "Šta znači 'Herzlichen Glückwunsch'?", options: ["Laku noć", "Dobar dan", "Srećan rođendan / Čestitam", "Hvala"], answer: 2 },
  { id: "n100", subject: "Nemački jezik", question: "Kako se kaže 'Nemačka' na nemačkom?", options: ["Österreich", "Schweiz", "Deutschland", "Frankreich"], answer: 2 },
];
